### PR TITLE
feat: add firefish button

### PR DESCRIPTION
**Pull request by LeviSnoot**
image

Firefish also uses rel="me" for verification so I pretty much copied the code for Mastodon. Lemme know if something's wrong.

### CODE REVIEW

**Comment by JulianPrieber** [comment]
Someone used the thing!

**Comment by JulianPrieber** [comment]
@LeviSnoot do we need a separate `@case('firefish')` for this?

**Comment by JulianPrieber** [comment]
If we now have multiple rel me thingies, we might want to implement somehting like this:

```
@php
  $relMe = "mastodon, firefish";
  $relMeList = explode(', ', $relMe);
@endphp

@foreach($links as $link)
  @if(in_array($link->name, $relMeList))
    <link href="{{$link->link}}" rel="me">
  @endif
@endforeach
```

**Comment by LeviSnoot** [comment]
> @LeviSnoot do we need a separate `@case('firefish')` for this?

@JulianPrieber No. I'm not read up on PHP at all but it seems like the code you suggested did what we wanted:
image

If this looks good to you I'll pull it to this PR.

https://github.com/LeviSnoot/LinkStack/blob/1dbd7a2d6505d9b4c44c0111e0209f1134ce4856/resources/views/littlelink.blade.php#L8-L18

**Comment by MagicLike** [comment]
tagging @ThatOneCalculator

**Comment by ThatOneCalculator** [comment]
Nice!!

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/LinkStack/commit/87aa73ee6aeaa1797aae6bf4f48e592fc6e6bf52

**Pull request merged**
