### PR TITLE
Added buttons - BOOTH, HearThis.at, Pronouns.page and Throne

### PR DESCRIPTION
**Pull request by Realmlist**
Added styles, seeds and SVGs for BOOTH, HearThis.at, Pronouns.Page, and Throne.

### CODE REVIEW

**Comment by JulianPrieber** [comment]
Moved to `v4.6.1`

**Comment by JulianPrieber** [comment]
[pronounspage.svg](https://github.com/LinkStackOrg/LinkStack/pull/646/files#diff-3e310e4cfe287370ac69a8d7c0edb8ae702edb764c658450761235ed30da08dd) is not centered correctly

**Comment by JulianPrieber** [comment]
https://en.pronouns.page/design

**Comment by JulianPrieber** [comment]
Gonna fix this in main

**Comment by Realmlist** [comment]
> [pronounspage.svg](https://github.com/LinkStackOrg/LinkStack/pull/646/files#diff-3e310e4cfe287370ac69a8d7c0edb8ae702edb764c658450761235ed30da08dd) is not centered correctly

My apologies! I must've missed that. 🙏

**Pull request merged**
