### PR TITLE
Adding partial catalan translation

### PR DESCRIPTION
**Pull request by francescroycampderros**
Adding partial Catalan translation. Creating a new 'ca' folder inside 'resources/lang' with its 'messages.php' file.

### CODE REVIEW

**Comment by JulianPrieber** [comment]
Thank you for contributing @francescroycampderros!

What does "partial" mean here? Are some keys missing? What's the status here?

**Comment by francescroycampderros** [comment]
Sorry by "partial" I meant incomplete, I will need some more days to finish it.

**Comment by JulianPrieber** [comment]
Alright 👍

**Review by JulianPrieber — CHANGES_REQUESTED** [review]
Finish translation

**Comment by JulianPrieber** [comment]
Huh?

**Comment by JulianPrieber** [comment]
Did we just merge this?

**Comment by lastsamurai26** [comment]
Why not ? 
Or we will create a repos with languages ?

**Comment by lastsamurai26** [comment]
> Maybe I missed something, but we had this pull request on revision due to it not being finished. Are we managing this language on the Discord?

It may have happened, but I'm not sure if we should integrate them all but possibly as a separate repo. So that we only have German English and then in a separate repo the languages ?

**Comment by JulianPrieber** [comment]
A separate repo might actually be better. I think we should switch to that for v5.

**Comment by JulianPrieber** [comment]
@francescroycampderros Please open another pull request once you finish the translation.

**Pull request merged**
