### PR TITLE
Update messages.php

### PR DESCRIPTION
**Pull request by LeoColman**
This PR updates some of the automatically generated PTBR messages to a more natural sounding wording.

### CODE REVIEW

**Comment by LeoColman** [comment]
WTF @JulianPrieber I hadn't even checked what I had commited yet

**Comment by JulianPrieber** [comment]
Imma throw it into the latest beta

**Comment by LeoColman** [comment]
I'm just surprised it took less than 1 minute from commit to upstream merge 😂 
The translations should be fine.

**Comment by JulianPrieber** [comment]
No syntax issues. Let me know if there is more to change.
Live in `v4.6.0-beta-4`

**Pull request merged**
