### PR TITLE
Updated trakt.tv logo

### PR DESCRIPTION
**Pull request by LeviSnoot**
Did my best to follow their updated [branding requirements](https://trakt.tv/branding) while making it suitable for LinkStack.

### CODE REVIEW

**Comment by MattDevTec** [comment]
@LeviSnoot I am going to go through All of the current icons for all Predefined Links. 

If we are not using the most current logo, It will be updated.

**Comment by JulianPrieber** [comment]
What's the state of this PR?

**Comment by LeviSnoot** [comment]
> What's the state of this PR?

It's good to go but I'm not sure how @MattDevTec's comment affects things?

**Comment by JulianPrieber** [comment]
Appreciate it @LeviSnoot, I thought we had some sort of issue here,
Gonna merge it now.

**Comment by JulianPrieber** [comment]
Implemented in `v4.8.4-beta-6`

**Pull request merged**
