### PR TITLE
Adding more socials to LinkStack

### PR DESCRIPTION
**Pull request by nekosheen**
List of socials added or uncommented:
- Telegram
- Whatsapp
- Behance
- Dribble

Screen Shot 2024-08-18 at 12 07 05

### CODE REVIEW

**Comment by JulianPrieber** [comment]
We should probably figure out a dynamic way of adding these.

**Comment by JulianPrieber** [comment]
Gonna merge this for `v4.8.1`

**Comment by nekosheen** [comment]
> We should probably figure out a dynamic way of adding these.

@JulianPrieber We could pull all the "social" from bootstrap icon for example, ensuring we have an icon to match, here's the query https://icons.getbootstrap.com/?q=social, a bit of parsing and we could get the name pretty easily I think

**Comment by JulianPrieber** [comment]
Something like this would probably be ideal 
image

**Pull request merged**
